import {
    IconReorder,
    IconDeveloperBoard,
    IconDomain,
    IconReceipt,
    IconViewList,
    IconGavel,
    IconLibraryBooks,
    IconListAlt,
    IconForum,
    IconAccountBalanceWallet,
    IconSettingsCell,
    IconTune,
    IconInfo,
    IconCheckCircle,
    IconContacts,
    IconAcUnit,
    IconToc,
    IconAccoutTree,
    IconExtension,
    IconUtilities,
    IconExports,
    IconAllTransactions,
    IconReportSharp,
    IconGeneralSettings,
    IconDone,
    IconDoneAll,
    IconDoneOutline,
    IconMoney,
    IconMoneyOff,
    IconPayment,
    IconAccountBalance,
    DeleteForever,
    HighlightOff,
    DeleteRounded,
    MoneyIcon,
    DeleteTwoTone,
    People,
    SalesAndPurchases,
    SalesReturn,
    PurchaseReturn,
    DebitNotes,
    CreditNotes,
    Inventory,
    Categories,
    AccountTree,
    LibraryBooks,
} from '../imports/icons-import'

const iconMap: any = {
    finalAccountsMenu: <IconAccountBalance></IconAccountBalance>,
    trialBalanceSubMenu: <IconDone></IconDone>,
    balanceSheetSubMenu: <IconDoneAll></IconDoneAll>,
    profitLossSubMenu: <IconDoneOutline></IconDoneOutline>,
    generalLedgerSubMenu: <LibraryBooks />,
    taxationSubMenu: <IconPayment />,

    vouchersMenu: <IconViewList></IconViewList>,
    paymentsSubMenu: <IconPayment></IconPayment>,
    receiptsSubMenu: <IconReceipt></IconReceipt>,
    contraSubMenu: <IconLibraryBooks></IconLibraryBooks>,
    journalsSubMenu: <IconGavel></IconGavel>,

    optionsMenu: <IconExtension></IconExtension>,
    bankReconSubMenu: <IconReorder></IconReorder>,
    incomeSubMenu: <MoneyIcon></MoneyIcon>,
    genericExportsSubMenu: <IconExports></IconExports>,
    commonUtilitiesSubMenu: <IconUtilities></IconUtilities>,

    mastersMenu: <IconListAlt></IconListAlt>,
    unitInfoSubMenu: <IconInfo></IconInfo>,
    generalSettingsSubMenu: <IconGeneralSettings></IconGeneralSettings>,
    accountsSubMenu: <IconForum></IconForum>,
    accountsOpBalSubMenu: <IconAccountBalanceWallet></IconAccountBalanceWallet>,
    branchesSubMenu: <IconSettingsCell></IconSettingsCell>,
    financialYearsSubMenu: <IconTune></IconTune>,

    reportsMenu: <IconReportSharp></IconReportSharp>,
    allTransactionsSubMenu: <IconAllTransactions></IconAllTransactions>,

    //Sales and purchases menu
    salesPurchasesMenu: <SalesAndPurchases></SalesAndPurchases>,
    salesSubMenu: <IconMoney></IconMoney>,
    purchasesSubMenu: <IconMoneyOff></IconMoneyOff>,
    salesReturnSubMenu: <SalesReturn></SalesReturn>,
    purchaseReturnSubMenu: <PurchaseReturn></PurchaseReturn>,
    debitNotesSubMenu: <DebitNotes></DebitNotes>,
    creditNotesSubMenu: <CreditNotes></CreditNotes>,

    // Inventory menu
    inventoryMenu: <Inventory></Inventory>,
    brandsSubMenu: <AccountTree />,
    categoriesSubMenu: <Categories></Categories>,
    productsSubMenu: <LibraryBooks />,

    //Admin menu
    artifacts: <IconCheckCircle></IconCheckCircle>,
    manageUsers: <IconContacts></IconContacts>,
    manageBu: <IconAcUnit></IconAcUnit>,
    manageRoles: <People></People>,
    associateBusinessUsersWithRolesAndBu: <IconToc></IconToc>,

    // Super admin menu
    manageClients: <IconAccoutTree></IconAccoutTree>,
    manageEntities: <IconDomain></IconDomain>,
    associateAdminUserWithClientAndEntity: (
        <IconDeveloperBoard></IconDeveloperBoard>
    ),

    permanentDelete: <DeleteForever></DeleteForever>,
    deleteAdminUser: <HighlightOff></HighlightOff>,
    deleteClient: <DeleteRounded></DeleteRounded>,
    deleteEntity: <DeleteTwoTone></DeleteTwoTone>,
}

export { iconMap }
