; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ExportService"
#define MyAppVersion "1.0"
#define MyAppPublisher "Sushant Agrawal"
#define MyAppURL "http://www.sushantagrawal.com"
#define MyAppExeName "ExportService.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8C9319AC-E5FC-452F-B2A1-779BD12D23F0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesInstallIn64BitMode=x64
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=ExportService setup
SetupIconFile=C:\projects\trace\dev\export-service-sale-py\inno-setup\service-export.ico.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\projects\trace\dev\export-service-sale-py\config.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\trace\dev\export-service-sale-py\dist\ExportService.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: "HKLM64"; Subkey: "SOFTWARE\ODBC\ODBC.INI\service"; ValueType: string; ValueName: "AutoStop"; ValueData: "Yes"; Flags: createvalueifdoesntexist
Root: "HKLM64"; Subkey: "SOFTWARE\ODBC\ODBC.INI\service"; ValueType: string; ValueName: "CommLinks"; ValueData: "TCPIP{{}"; Flags: createvalueifdoesntexist
Root: "HKLM64"; Subkey: "SOFTWARE\ODBC\ODBC.INI\service"; ValueType: string; ValueName: "Compress"; ValueData: "No"; Flags: createvalueifdoesntexist
Root: "HKLM64"; Subkey: "SOFTWARE\ODBC\ODBC.INI\service"; ValueType: string; ValueName: "DatabaseName"; ValueData: "service"; Flags: createvalueifdoesntexist
Root: "HKLM64"; Subkey: "SOFTWARE\ODBC\ODBC.INI\service"; ValueType: string; ValueName: "Driver"; ValueData: "C:\Program Files\SQL Anywhere 11\Bin64\dbodbc11.dll"; Flags: createvalueifdoesntexist
Root: "HKLM64"; Subkey: "SOFTWARE\ODBC\ODBC.INI\service"; ValueType: string; ValueName: "EngineName"; ValueData: "server"; Flags: createvalueifdoesntexist
Root: "HKLM64"; Subkey: "SOFTWARE\ODBC\ODBC.INI\service"; ValueType: string; ValueName: "Integrated"; ValueData: "No"; Flags: createvalueifdoesntexist
Root: "HKLM64"; Subkey: "SOFTWARE\ODBC\ODBC.INI\service"; ValueType: string; ValueName: "PWD"; ValueData: "sql"; Flags: createvalueifdoesntexist
Root: "HKLM64"; Subkey: "SOFTWARE\ODBC\ODBC.INI\service"; ValueType: string; ValueName: "UID"; ValueData: "dba"; Flags: createvalueifdoesntexist
