import { PDFViewer } from '@react-pdf/renderer'
import { useEffect, useState } from 'react'
import { useComp2 } from './comp2-hook'
function Comp2() {
    const { InvoicePdf } = useComp2()
    const invoiceData = getInvoiceData(traceCompany, traceInvoiceIndividual)
    processInvoiceData(invoiceData)

    console.log(invoiceData)
    return (
        <PDFViewer width={760} height={800} >
            <InvoicePdf invoiceData={invoiceData} />
        </PDFViewer>
    )

    function getInvoiceData(traceCompany: any, traceInvoice: any) {
        const tc = traceCompany,
            ti = traceInvoice.jsonResult
        const i: {
            invoiceInfo: any
            companyInfo: any
            billTo: any
            shipTo: any
            items: any[]
            summary: any
            receipts: any[]
        } = {
            invoiceInfo: null,
            companyInfo: null,
            billTo: null,
            shipTo: null,
            items: [],
            summary: null,
            receipts: [],
        }
        i.invoiceInfo = {
            title: 'Tax Invoice',
            titleRight: 'Original for recipient',
            invoiceNo: ti.tranH.autoRefNo,
            invoiceDate: ti.tranH.tranDate,
            type: ti.tranH.tranTypeId == 4 ? 'Sale' : 'Sale Ret',
            terms: '',
        }
        i.companyInfo = {
            name: tc.unitName,
            address1: tc.address1,
            address2: tc.address2,
            pin: tc.pin,
            phone: ''.concat(tc.landPhone, ' ', tc.mobileNumber),
            email: tc.email,
            web: tc.webSite,
            gstin: tc.gstin,
            stateName: 'West Bengal', // Get from stateCode from data
            stateCode: tc.state,
        }
        const billTo = ti.billTo || ti.businessContacts
        i.billTo = {
            name: billTo.contactName,
            address1: billTo.address1,
            address2: billTo.address2,
            pin: billTo.pin || billTo.jAddress?.pin,
            phone: ''.concat(billTo.mobileNumber || '', ' ', billTo.landPhone || ''),
            email: billTo.email,
            gstin: billTo.gstin,
            stateName: billTo.state || billTo.jAddress?.state,
            stateCode: billTo.stateCode,
        }
        const shipTo = ti.tranH.jData?.shipTo
        i.shipTo = {
            name: shipTo?.contactName || '',
            address1: shipTo?.address1 || '',
            address2: shipTo?.address2 || '',
            pin: shipTo?.pin || '',
            phone: shipTo?.mobileNumber || '',
            email: shipTo?.email || '',
            state: shipTo?.state || '',
            country: shipTo?.country || ''
        }
        i.items = ti.salePurchaseDetails.map((x: any) => ({
            desc: ''.concat(
                x.catName,
                ', ',
                x.brandName,
                ', ',
                x.label,
                ', ',
                'Serial nos ',
                x.serialNumbers,
                ', HSN ',
                x.hsn
            ),
            qty: x.qty,
            cgst: x.cgst,
            sgst: x.sgst,
            igst: x.igst,
            gst: x.cgst + x.sgst + x.igst,
            aggr: (x.price * x.qty) - x.discount,
            price: x.price,
            pricegst: x.priceGst,
            gstRate: x.gstRate,
            discount: x.discount,
            amount: x.amount,
        }))
        const gst = ti.extGstTranD
        const amt = 20000
        i.summary = {
            cgst: gst?.cgst || 0.00,
            sgst: gst?.sgst || 0.00,
            igst: gst?.igst || 0.00,
            amount: 20000,
            aggr: amt -  ((gst?.cgst || 0) + (gst?.cgst || 0) + (gst?.igst || 0)),
             // calculate amount from tranD
        }
        i.receipts = [{
            type: 'credit card',
            instrument: '23223',
            remarks:'Citi Bank',
            amount: 2000
        },
        {
            type: 'debit card',
            instrument: '28873',
            remarks:'HDFC Bank',
            amount: 11000
        },
        {
            type: 'ETransfer',
            instrument: '78778888888',
            remarks:'PAYTM',
            amount: 1000
        }
    ]
        return i
    }

    function processInvoiceData(invoiceData: any) {
        // update sale terms
        // update transactions
        // update summary
    }
}
export { Comp2 }

const traceCompany = {
    pin: '700067',
    email: 'invest@gmail.com',
    gstin: '19AACCC5685L1Z3',
    state: '19',
    webSite: 'www.capital-investments.com',
    address1: '12, Ko Chi Minch Sarani, Efteel Towers',
    address2: 'Behind Kutub Minar',
    unitName: 'Capital Investments Pvt Ltd',
    landPhone: '23551699',
    shortName: 'capitalInvestments',
    mobileNumber: '9155632145',
}

const traceInvoiceIndividual = {
    "jsonResult":{
       "tranH":{
          "id":9945,
          "tranDate":"2021-11-28",
          "userRefNo":null,
          "remarks":null,
          "autoRefNo":"head\\SAL\\2912\\2021",
          "jData":{
             "shipTo":{
                "pin":"755587",
                "city":"Kol",
                "email":"csd@gmail.com",
                "state":"WB",
                "country":"India",
                "address1":"12 Jagmohan Dalmia Street",
                "contactName":"Ambala enterprises",
                "mobileNumber":"9875655445"
             }
          },
          "tranTypeId":4
       },
       "billTo":{
          "id":143,
          "contactName":"Blaze Clay",
          "mobileNumber":"7104049395",
          "otherMobileNumber":"5943599701",
          "landPhone":null,
          "email":"sed.facilisis@Aliquam.com",
          "descr":null,
          "jData":null,
          "anniversaryDate":null,
          "address1":"Ap #706-340 Non St.",
          "address2":"4281 Iaculis Street",
          "country":"Antarctica",
          "state":"Alberta",
          "city":"Breton",
          "gstin":null,
          "pin":"51213",
          "dateOfBirth":null,
          "stateCode":null,
          "timestamp":"2021-03-25T09:56:39.710278+00:00"
       },
       "businessContacts":null,
       "tranD":[
          {
             "id":19775,
             "accId":167,
             "dc":"C",
             "amount":44000,
             "instrNo":null,
             "remarks":null
          },
          {
             "id":19776,
             "accId":118,
             "dc":"D",
             "amount":44000,
             "instrNo":null,
             "remarks":""
          }
       ],
       "extGstTranD":{
          "id":9670,
          "gstin":null,
          "cgst":0,
          "sgst":0,
          "igst":0
       },
       "salePurchaseDetails":[
          {
             "id":9582,
             "productId":10,
             "qty":2,
             "price":22000,
             "priceGst":22000,
             "discount":0,
             "cgst":100,
             "sgst":200,
             "igst":0,
             "amount":44000,
             "hsn":55542,
             "gstRate":18,
             "productCode":"1001",
             "upcCode":"2",
             "catName":"OLED",
             "brandName":"SONY",
             "info":"",
             "label":"REC-002 This is new but good model, good for nothing, for testing",
             "serialNumbers":"333,rrr",
             "remarks":null
          },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-002 This is new but good model, good for nothing, for testing",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-002 This is new but good model, good for nothing, for testing",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-002 This is new but good model, good for nothing, for testing",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        }
       ]
    }
 }

const traceInvoiceParty = {
    jsonResult: {
        tranH: {
            id: 9931,
            tranDate: '2021-11-17',
            userRefNo: null,
            remarks: null,
            autoRefNo: 'head\\SAL\\2908\\2021',
            jData: null,
        },
        billTo: null,
        businessContacts: {
            id: 4,
            contactName: 'Billenium sales pvt ltd',
            contactCode: 'billeniumSales',
            mobileNumber: '9555421232',
            otherMobileNumber: '',
            landPhone: '235512254',
            email: 'bille@fgg.com',
            otherEmail: '',
            jAddress: [
                {
                    pin: '7000013',
                    city: 'Kolkata',
                    state: 'West Bengal',
                    country: 'India',
                    address1: '23, Tootie lane',
                    address2: '',
                },
            ],
            descr: '',
            accId: 159,
            jData: null,
            gstin: '37AADCB2230M2ZR',
            timestamp: '2021-03-25T09:58:01+00:00',
            stateCode: 19,
        },
        tranD: [
            {
                id: 19745,
                accId: 167,
                dc: 'C',
                amount: 5600,
                instrNo: null,
                remarks: null,
            },
            {
                id: 19746,
                accId: 159,
                dc: 'D',
                amount: 5600,
                instrNo: null,
                remarks: '',
            },
        ],
        extGstTranD: {
            id: 9663,
            gstin: '37AADCB2230M2ZR',
            cgst: 300,
            sgst: 300,
            igst: 0,
        },
        salePurchaseDetails: [
            {
                id: 9570,
                productId: 12,
                qty: 1,
                price: 5000,
                priceGst: 5600,
                discount: 0,
                cgst: 300,
                sgst: 300,
                igst: 0,
                amount: 5600,
                hsn: 2222,
                gstRate: 12,
                productCode: '1003',
                upcCode: '4',
                catName: 'OLED',
                brandName: 'SONY',
                info: '',
                label: 'eeewwswqw',
                serialNumbers: '',
                remarks: null,
            },
        ],
    },
}
