import { useSharedElements } from '../../common/shared-elements-hook'
import { useInvoiceA, } from './invoiceA-hook'
import { moment } from '../../../../../imports/regular-imports'

function InvoiceA({ rawSaleData, unitInfo }: any) {
    const { getFromBag, toDecimalFormat} = useSharedElements()
    const { InvoicePdf } = useInvoiceA()
    const dateFormat = getFromBag('dateFormat')
   //  const invoiceData = getInvoiceData(traceCompany, traceInvoiceIndividual)
    const invoiceData = getInvoiceData(unitInfo, rawSaleData)
    processInvoiceData(invoiceData)

    return <InvoicePdf invoiceData={invoiceData} />

    function getInvoiceData(traceCompany: any, traceInvoice: any) {
        const tc = traceCompany,
            ti = traceInvoice.jsonResult
        const i: {
            invoiceInfo: any
            companyInfo: any
            billTo: any
            shipTo: any
            items: any[]
            summary: any
            receipts: any[]
        } = {
            invoiceInfo: null,
            companyInfo: null,
            billTo: null,
            shipTo: null,
            items: [],
            summary: null,
            receipts: [],
        }
        i.invoiceInfo = {
            title: 'Tax Invoice',
            titleRight: 'Original for recipient',
            invoiceNo: ti.tranH.autoRefNo,
            invoiceDate:  moment(ti.tranH.tranDate).format(dateFormat),
            type: ti.tranH.tranTypeId == 4 ? 'Sale' : 'Sale Ret',
            terms: '',
        }
        i.companyInfo = {
            name: tc.unitName,
            address1: tc.address1,
            address2: tc.address2,
            pin: tc.pin,
            phone: ''.concat(tc.landPhone, ' ', tc.mobileNumber),
            email: tc.email,
            web: tc.webSite,
            gstin: tc.gstin,
            stateName: 'West Bengal', // Get from stateCode from data
            stateCode: tc.state,
        }
        const billTo = ti.billTo || ti.businessContacts
        i.billTo = {
            name: billTo.contactName,
            address1: billTo.address1,
            address2: billTo.address2,
            pin: billTo.pin || billTo.jAddress?.pin,
            phone: ''.concat(billTo.mobileNumber || '', ' ', billTo.landPhone || ''),
            email: billTo.email,
            gstin: billTo.gstin,
            stateName: billTo.state || billTo.jAddress?.state,
            stateCode: billTo.stateCode,
        }
        const shipTo = ti.tranH.jData?.shipTo
        i.shipTo = {
            name: shipTo?.contactName || '',
            address1: shipTo?.address1 || '',
            address2: shipTo?.address2 || '',
            pin: shipTo?.pin || '',
            phone: shipTo?.mobileNumber || '',
            email: shipTo?.email || '',
            state: shipTo?.state || '',
            country: shipTo?.country || ''
        }
        i.items = ti.salePurchaseDetails.map((x: any) => ({
            desc: ''.concat(
                x.catName,
                ', ',
                x.brandName,
                ', ',
                x.label,
                x.serialNumbers ? ', Sl nos:'.concat(x.serialNumbers): '',
                ', HSN ',
                x.hsn
            ),
            qty: x.qty,
            cgst: toDecimalFormat(x.cgst),
            sgst: toDecimalFormat(x.sgst),
            igst: toDecimalFormat(x.igst),
            gst: toDecimalFormat(x.cgst + x.sgst + x.igst),
            aggr: toDecimalFormat((x.price * x.qty) - x.discount),
            price: toDecimalFormat(x.price),
            pricegst: toDecimalFormat(x.priceGst),
            gstRate: toDecimalFormat(x.gstRate),
            discount: toDecimalFormat(x.discount),
            amount: toDecimalFormat(x.amount),
        }))
        const gst = ti.extGstTranD
        const amt = 20000
        i.summary = {
            cgst: gst?.cgst || 0.00,
            sgst: gst?.sgst || 0.00,
            igst: gst?.igst || 0.00,
            amount: 20000,
            aggr: amt -  ((gst?.cgst || 0) + (gst?.cgst || 0) + (gst?.igst || 0)),
             // calculate amount from tranD
        }
        i.receipts = [{
            type: 'credit card',
            instrument: '23223',
            remarks:'Citi Bank',
            amount: 2000
        },
        {
            type: 'debit card',
            instrument: '28873',
            remarks:'HDFC Bank',
            amount: 11000
        },
        {
            type: 'ETransfer',
            instrument: '78778888888',
            remarks:'PAYTM',
            amount: 1000
        }
    ]
        return i
    }

    function processInvoiceData(invoiceData: any) {
        // update sale terms
        // update transactions
        // update summary
    }
}

export { InvoiceA }

const traceCompany = {
    pin: '700067',
    email: 'invest@gmail.com',
    gstin: '19AACCC5685L1Z3',
    state: '19',
    webSite: 'www.capital-investments.com',
    address1: '12, Ko Chi Minch Sarani, Efteel Towers',
    address2: 'Behind Kutub Minar',
    unitName: 'Capital Investments Pvt Ltd',
    landPhone: '23551699',
    shortName: 'capitalInvestments',
    mobileNumber: '9155632145',
}

const traceInvoiceIndividual = {
    "jsonResult":{
       "tranH":{
          "id":9945,
          "tranDate":"2021-11-28",
          "userRefNo":null,
          "remarks":null,
          "autoRefNo":"head\\SAL\\2912\\2021",
          "jData":{
             "shipTo":{
                "pin":"755587",
                "city":"Kol",
                "email":"csd@gmail.com",
                "state":"WB",
                "country":"India",
                "address1":"12 Jagmohan Dalmia Street",
                "contactName":"Ambala enterprises",
                "mobileNumber":"9875655445"
             }
          },
          "tranTypeId":4
       },
       "billTo":{
          "id":143,
          "contactName":"Blaze Clay",
          "mobileNumber":"7104049395",
          "otherMobileNumber":"5943599701",
          "landPhone":null,
          "email":"sed.facilisis@Aliquam.com",
          "descr":null,
          "jData":null,
          "anniversaryDate":null,
          "address1":"Ap #706-340 Non St.",
          "address2":"4281 Iaculis Street",
          "country":"Antarctica",
          "state":"Alberta",
          "city":"Breton",
          "gstin":null,
          "pin":"51213",
          "dateOfBirth":null,
          "stateCode":null,
          "timestamp":"2021-03-25T09:56:39.710278+00:00"
       },
       "businessContacts":null,
       "tranD":[
          {
             "id":19775,
             "accId":167,
             "dc":"C",
             "amount":44000,
             "instrNo":null,
             "remarks":null
          },
          {
             "id":19776,
             "accId":118,
             "dc":"D",
             "amount":44000,
             "instrNo":null,
             "remarks":""
          }
       ],
       "extGstTranD":{
          "id":9670,
          "gstin":null,
          "cgst":0,
          "sgst":0,
          "igst":0
       },
       "salePurchaseDetails":[
          {
             "id":9582,
             "productId":10,
             "qty":2,
             "price":22000,
             "priceGst":22000,
             "discount":0,
             "cgst":100,
             "sgst":200,
             "igst":0,
             "amount":44000,
             "hsn":55542,
             "gstRate":18,
             "productCode":"1001",
             "upcCode":"2",
             "catName":"OLED",
             "brandName":"SONY",
             "info":"",
             "label":"REC-002 This is new but good model, good for nothing, for testing",
             "serialNumbers":"333,rrr",
             "remarks":null
          },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-002 This is new but good model, good for nothing, for testing",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-001",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
            "id":9582,
            "productId":10,
            "qty":2,
            "price":22000,
            "priceGst":22000,
            "discount":0,
            "cgst":100,
            "sgst":200,
            "igst":0,
            "amount":44000,
            "hsn":55542,
            "gstRate":18,
            "productCode":"1001",
            "upcCode":"2",
            "catName":"OLED",
            "brandName":"SONY",
            "info":"",
            "label":"REC-002 This is new but good model, good for nothing, for testing",
            "serialNumbers":"333,rrr",
            "remarks":null
         },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-002 This is new but good model, good for nothing, for testing",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        },{
           "id":9582,
           "productId":10,
           "qty":2,
           "price":22000,
           "priceGst":22000,
           "discount":0,
           "cgst":100,
           "sgst":200,
           "igst":0,
           "amount":44000,
           "hsn":55542,
           "gstRate":18,
           "productCode":"1001",
           "upcCode":"2",
           "catName":"OLED",
           "brandName":"SONY",
           "info":"",
           "label":"REC-001",
           "serialNumbers":"333,rrr",
           "remarks":null
        }
       ]
    }
 }