import {
    AccountBalance as IconAccountBalance,
    AccountTree as IconAccoutTree,
    AcUnit as IconAcUnit,
    AccountBalanceWallet as IconAccountBalanceWallet,
    ArrowDropDownSharp as ArrowDropDown,
    Build as IconUtilities,
    CheckCircle as IconCheckCircle,
    Contacts as IconContacts,
    CloseSharp as CloseIcon,
    DeveloperBoard as IconDeveloperBoard,
    Domain as IconDomain,
    Done as IconDone,
    DoneAll as IconDoneAll,
    DoneOutline as IconDoneOutline,
    Extension as IconExtension,
    Forum as IconForum,
    Gavel as IconGavel,
    Info as IconInfo,
    Money as IconMoney,
    MoneyOff as IconMoneyOff,
    Payment as IconPayment,
    Receipt as IconReceipt,
    Reorder as IconReorder,
    ReportSharp as IconReportSharp,
    ViewList as IconViewList,
    Settings as IconGeneralSettings,
    SettingsCell as IconSettingsCell,
    SupervisorAccount as SupervisorIcon,
    Toc as IconToc,
    Tune as IconTune,
    AccountCircleSharp as SuperAdminIcon,
    SecuritySharp as ChangeUidIcon,
    VerifiedUserSharp as ChangePasswordicon,
    ExitToAppSharp as LogoutIcon,
    LibraryBooks as IconLibraryBooks,
    ListAlt as IconListAlt,
    SystemUpdate as IconExports,
    ViewListSharp as IconAllTransactions,
    Menu as MenuIcon,
} from '@material-ui/icons'

import {
    DeleteForever,
    HighlightOff,
    DeleteRounded,
    MonetizationOn as MoneyIcon,
    DeleteTwoTone,
    People,
    DynamicFeed as SalesAndPurchases,
    AssignmentReturn as SalesReturn,
    AssignmentReturned as PurchaseReturn,
    FlightLand as DebitNotes,
    FlightTakeoff as CreditNotes,
    Dialpad as Inventory,
    Category as Categories,
    AccountTree,
    LibraryBooks,
} from '@material-ui/icons'

export {
    AccountTree,
    ArrowDropDown,
    Categories,
    ChangePasswordicon,
    ChangeUidIcon,
    CloseIcon,
    IconInfo,
    CreditNotes,
    DebitNotes,
    DeleteForever,
    DeleteRounded,
    DeleteTwoTone,
    HighlightOff,
    IconAccoutTree,
    IconAcUnit,
    IconAccountBalance,
    IconAccountBalanceWallet,
    IconContacts,
    IconCheckCircle,
    IconDeveloperBoard,
    IconDomain,
    IconDone,
    IconDoneAll,
    IconDoneOutline,
    IconExports,
    IconExtension,
    IconForum,
    IconGavel,
    IconListAlt,
    IconMoney,
    IconMoneyOff,
    IconPayment,
    IconReceipt,
    IconAllTransactions,
    IconGeneralSettings,
    IconLibraryBooks,
    IconReportSharp,
    IconSettingsCell,
    IconReorder,
    IconToc,
    IconTune,
    IconUtilities,
    IconViewList,
    Inventory,
    LibraryBooks,
    LogoutIcon,
    MenuIcon,
    MoneyIcon,
    People,
    PurchaseReturn,
    SalesAndPurchases,
    SalesReturn,
    SuperAdminIcon,
    SupervisorIcon,
}
