import {
    AccountBalance as IconAccountBalance,
    AccountTree as IconAccoutTree,
    AcUnit as IconAcUnit,
    AccountBalanceWallet as IconAccountBalanceWallet,
    ArrowDropDownSharp as ArrowDropDown,
    Build as IconUtilities,
    CheckCircle as IconCheckCircle,
    Contacts as IconContacts,
    CloseSharp as CloseIcon,
    DeveloperBoard as IconDeveloperBoard,
    Domain as IconDomain,
    Done as IconDone,
    DoneAll as IconDoneAll,
    DoneOutline as IconDoneOutline,
    Extension as IconExtension,
    Forum as IconForum,
    Gavel as IconGavel,
    Info as IconInfo,
    Money as IconMoney,
    MoneyOff as IconMoneyOff,
    Payment as IconPayment,
    Receipt as IconReceipt,
    Reorder as IconReorder,
    ReportSharp as IconReportSharp,
    ViewList as IconViewList,
    Settings as IconGeneralSettings,
    SettingsCell as IconSettingsCell,
    SupervisorAccount as SupervisorIcon,
    Toc as IconToc,
    Tune as IconTune,
    AccountCircleSharp as SuperAdminIcon,
    SecuritySharp as ChangeUidIcon,
    VerifiedUserSharp as ChangePasswordicon,
    ExitToAppSharp as LogoutIcon,
    LibraryBooks as IconLibraryBooks,
    ListAlt as IconListAlt,
    SystemUpdate as IconExports,
    ViewListSharp as IconAllTransactions,
    Menu as MenuIcon,
} from '@mui/icons-material' // '@material-ui/icons'

import {
    DeleteForever,
    ExpandLess as IconExpandLess,
    ExpandMore as IconExpandMore,
    ChevronLeft as ChevronLeftIcon,
    ChevronRight as ChevronRightIcon,
    HighlightOff,
    DeleteRounded,
    MonetizationOn as MoneyIcon,
    DeleteTwoTone,
    PageviewTwoTone,
    People,
    Search as SearchIcon,
    Save as SaveIcon,
    Send as SendIcon,
    DynamicFeed as SalesAndPurchases,
    AssignmentReturn as SalesReturn,
    AssignmentReturned as PurchaseReturn,
    FlightLand as DebitNotes,
    FlightTakeoff as CreditNotes,
    Dialpad as Inventory,
    Category as Categories,
    AccountTree,
    LibraryBooks,
} from '@mui/icons-material' // '@material-ui/icons'

import {
    Add as AddIcon,
    AddCircle,
    AddBox,
    ArrowDownward,
    Cached as RefreshIcon,
    Check,
    Clear,
    ClearAll,
    DeleteOutline,
    Edit,
    Edit as EditIcon,
    Error as ErrorIcon,
    FilterList,
    FirstPage,
    FlipToFront as RearrangeIcon,
    LastPage,
    Link as LinkIcon,
    Remove,
    RemoveCircleOutline as MinusIcon,
    RemoveCircle,
    SaveAlt,
    SyncSharp as SyncIcon,
    ViewColumn,
    ZoomIn as ZoomInIcon,
    ZoomOut as ZoomOutIcon
} from '@mui/icons-material' // '@material-ui/icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSpinner } from '@fortawesome/free-solid-svg-icons'

export {
    AddIcon,
    AddCircle,
    AccountTree,
    AddBox,
    ArrowDownward,
    ArrowDropDown,
    Categories,
    ChangePasswordicon,
    Check,
    ChangeUidIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    Clear,
    ClearAll,
    CloseIcon,
    ErrorIcon,
    IconInfo,
    CreditNotes,
    DebitNotes,
    DeleteForever,
    DeleteForever as DeleteIcon,
    DeleteOutline,
    DeleteRounded,
    DeleteTwoTone,
    Edit,
    EditIcon,
    faSpinner,
    FilterList,
    FirstPage,
    FontAwesomeIcon,
    IconExpandLess,
    LastPage,
    HighlightOff,
    IconAccoutTree,
    IconAcUnit,
    IconAccountBalance,
    IconAccountBalanceWallet,
    IconContacts,
    IconCheckCircle,
    IconDeveloperBoard,
    IconDomain,
    IconDone,
    IconDoneAll,
    IconDoneOutline,
    IconExpandMore,
    IconExports,
    IconExtension,
    IconForum,
    IconGavel,
    IconListAlt,
    IconMoney,
    IconMoneyOff,
    IconPayment,
    IconReceipt,
    IconAllTransactions,
    IconGeneralSettings,
    IconLibraryBooks,
    IconReportSharp,
    IconSettingsCell,
    IconReorder,
    IconToc,
    IconTune,
    IconUtilities,
    IconViewList,
    Inventory,
    LibraryBooks,
    LinkIcon,
    LogoutIcon,
    MenuIcon,
    MinusIcon,
    MoneyIcon,
    People,
    PageviewTwoTone,
    PurchaseReturn,
    RearrangeIcon,
    RefreshIcon,
    Remove,
    RemoveCircle,
    SaveAlt,
    SaveIcon,
    SalesAndPurchases,
    SalesReturn,
    SearchIcon,
    SendIcon,
    SyncIcon,
    SuperAdminIcon,
    SupervisorIcon,
    ViewColumn,
    ZoomInIcon,
    ZoomOutIcon,
}
