export {
    AccountBalance,
    AccountTree,
    AcUnit,
    AccountBalanceWallet,
    Add,
    AddCircle,
    AddBox,
    ArrowDownward,
    ArrowDropDownSharp,
    AssignmentReturn,
    AssignmentReturned,
    Build,
    Cached,
    Check,
    Clear,
    ClearAll,
    Category,
    CheckCircle,
    ChevronLeft,
    ChevronRight,
    Contacts,
    CloseSharp,
    DeleteTwoTone,
    DeleteForever,
    DeleteOutline,
    DeleteRounded,
    DeveloperBoard,
    Dialpad,
    Domain,
    Done,
    DoneAll,
    DoneOutline,
    DynamicFeed,
    Edit,
    Error,
    ExpandLess,
    ExpandMore,
    Extension,
    FilterList,
    FirstPage,
    FlipToFront,
    FlightLand,
    FlightTakeoff,
    Forum,
    Gavel,
    HighlightOff,
    Inventory,
    Info,
    LastPage,
    Link,
    Money,
    MonetizationOn,
    MoneyOff,
    PageviewTwoTone,
    Payment,
    People,
    Receipt,
    Reorder,
    Remove,
    RemoveCircleOutline,
    RemoveCircle,
    ReportSharp,    
    Save,
    SaveAlt,
    Search,
    Send,
    Settings,
    SettingsCell,
    SupervisorAccount,
    SyncSharp,
    Toc,
    Tune,
    AccountCircleSharp,
    SecuritySharp,
    VerifiedUserSharp,
    ExitToAppSharp,
    LibraryBooks,
    ListAlt,
    SystemUpdate,
    ViewColumn,
    ViewList,
    ViewListSharp,
    Menu,
    ZoomIn,
    ZoomOut
} from '@mui/icons-material'

export { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
export { faSpinner } from '@fortawesome/free-solid-svg-icons'

// import {
//     AccountBalance as AccountBalance,
//     AccountTree as AccoutTree,
//     AcUnit as AcUnit,
//     AccountBalanceWallet as AccountBalanceWallet,
//     ArrowDropDownSharpSharp as ArrowDropDownSharp,
//     Build as Build,
//     CheckCircle as CheckCircle,
//     Contacts as Contacts,
//     CloseSharp as CloseSharp,
//     DeveloperBoard as DeveloperBoard,
//     Domain as Domain,
//     Done as Done,
//     DoneAll as DoneAll,
//     DoneOutline as DoneOutline,
//     Extension as Extension,
//     Forum as Forum,
//     Gavel as Gavel,
//     Info as Info,
//     Money as Money,
//     MoneyOff as MoneyOff,
//     Payment as Payment,
//     Receipt as Receipt,
//     Reorder as Reorder,
//     ReportSharp as ReportSharp,
//     ViewList as ViewList,
//     Settings as Settings,
//     SettingsCell as SettingsCell,
//     SupervisorAccount as SupervisorAccount,
//     Toc as Toc,
//     Tune as Tune,
//     AccountCircleSharp as AccountCircleSharp,
//     SecuritySharp as SecuritySharp,
//     VerifiedUserSharp as VerifiedUserSharp,
//     ExitToAppSharp as ExitToAppSharp,
//     LibraryBooks as LibraryBooks,
//     ListAlt as ListAlt,
//     SystemUpdate as SystemUpdate,
//     ViewListSharp as ViewListSharp,
//     Menu as Menu,
// } from '@material-ui/icons' //'@mui/icons-material'

// import {
//     DeleteForever,
//     ExpandLess as ExpandLess,
//     ExpandMore as ExpandMore,
//     ChevronLeft as ChevronLeft,
//     ChevronRight as ChevronRight,
//     HighlightOff,
//     DeleteRounded,
//     MonetizationOn as MonetizationOn,
//     DeleteTwoTone,
//     PageviewTwoTone,
//     People,
//     Search as Search,
//     Save as Save,
//     Send as Send,
//     DynamicFeed as DynamicFeed,
//     AssignmentReturn as AssignmentReturn,
//     AssignmentReturned as AssignmentReturned,
//     FlightLand as FlightLand,
//     FlightTakeoff as FlightTakeoff,
//     Dialpad as Inventory,
//     Category as Categories,
//     AccountTree,
//     LibraryBooks,
// } from '@material-ui/icons' //'@mui/icons-material'

// import {
//     Add as Add,
//     AddCircle,
//     AddBox,
//     ArrowDownward,
//     Cached as Cached,
//     Check,
//     Clear,
//     ClearAll,
//     DeleteOutline,
//     Edit,
//     Edit as Edit,
//     Error as Error,
//     FilterList,
//     FirstPage,
//     FlipToFront as FlipToFront,
//     LastPage,
//     Link as LinkIcon,
//     Remove,
//     RemoveCircleOutline as RemoveCircleOutline,
//     RemoveCircle,
//     SaveAlt,
//     SyncSharp as SyncSharp,
//     ViewColumn,
//     ZoomIn as ZoomIn,
//     ZoomOut as ZoomOut
// } from   '@material-ui/icons' //'@mui/icons-material'


// export {
//     Add as Add,
//     AddCircle,
//     AccountTree,
//     AddBox,
//     ArrowDownward,
//     ArrowDropDownSharp,
//     Category as Categories,
//     VerifiedUserSharp as VerifiedUserSharp,
//     Check,
//     SecuritySharp as SecuritySharp,
//     ChevronLeft as ChevronLeft,
//     ChevronRight as ChevronRight,
//     Clear,
//     ClearAll,
//     CloseSharp as CloseSharp,
//     Error,
//     Info,
//     FlightTakeoff,
//     FlightLand,
//     DeleteForever,
//     DeleteForever as DeleteForever,
//     DeleteOutline,
//     DeleteRounded,
//     DeleteTwoTone,
//     Edit,
//     Edit,
//     // faSpinner,
//     FilterList,
//     FirstPage,
//     // FontAwesomeIcon,
//     ExpandLess,
//     LastPage,
//     HighlightOff,
//     AccountTree as AccoutTree,
//     AcUnit as AcUnit,
//     AccountBalance as AccountBalance,
//     AccountBalanceWallet as AccountBalanceWallet,
//     Contacts,
//     CheckCircle,
//     DeveloperBoard,
//     Domain,
//     Done,
//     DoneAll,
//     DoneOutline,
//     ExpandMore,
//     SystemUpdate,
//     Extension,
//     Forum,
//     Gavel,
//     ListAlt,
//     Money,
//     MoneyOff,
//     Payment,
//     Receipt,
//     ViewListSharp,
//     Settings,
//     LibraryBooks,
//     ReportSharp,
//     SettingsCell,
//     Reorder,
//     Toc,
//     Tune,
//     Build,
//     ViewList,
//     Inventory,
//     LibraryBooks,
//     LinkIcon,
//     ExitToAppSharp,
//     Menu,
//     RemoveCircleOutline,
//     MonetizationOn,
//     People,
//     PageviewTwoTone,
//     AssignmentReturned,
//     FlipToFront,
//     Cached,
//     Remove,
//     RemoveCircle,
//     SaveAlt,
//     Save,
//     DynamicFeed,
//     AssignmentReturn,
//     Search,
//     Send,
//     SyncSharp,
//     AccountCircleSharp,
//     SupervisorAccount,
//     ViewColumn,
//     ZoomIn,
//     ZoomOut,
// } from '@material-ui/icons'