// import TagIcon from '@mui/icons-material'
// export { Attachment } from '@mui/icons-material'
export {
    AccountBalance,
    AccountTree,
    AcUnit,
    AccountBalanceWallet,
    Add,
    AddCircle,
    AddBox,
    ArrowDownward,
    ArrowDropDownSharp,
    AssignmentReturn,
    AssignmentReturned,
    Attachment,
    // AttachmentSharp as AttachmentSharpIcon,
    AutoGraph,
    Build,
    Cached,
    Check,
    CheckBoxOutlineBlankSharp,
    CheckBoxOutlined,
    Clear,
    ClearAll,
    Category,
    CheckCircle,
    ChevronLeft,
    ChevronRight,
    Contacts,
    ContentCopySharp as Clone,
    CloseSharp,

    DeleteTwoTone,
    DeleteForever,
    DeleteOutline,
    DeleteRounded,
    DeveloperBoard,
    Dialpad,
    Domain,
    Done,
    DoneAll,
    DoneOutline,
    DynamicFeed,
    Edit,
    Email as EmailIcon,
    Error,
    ExpandLess,
    ExpandMore,
    Extension,
    FilterList,
    FirstPage,
    FlipToFront,
    FlightLand,
    FlightTakeoff,
    Forum,
    Gavel,
    HighlightOff,
    Inventory,
    Info,
    LastPage,
    LibraryBooks,
    Link,
    ListAlt,
    Money,
    MonetizationOn,
    MoneyOff,
    PageviewTwoTone,
    Payment,
    People,
    Preview,
    Print as PrintIcon,
    Receipt,
    Reorder,
    Remove,
    RemoveCircleOutline,
    RemoveCircle,
    ReportSharp,
    Save,
    SaveAlt,
    Search,
    Send,
    Settings,
    SettingsCell,
    Sms as SmsIcon,
    SupervisorAccount,
    SyncSharp,

    Toc,
    Tune,
    AccountCircleSharp,
    SecuritySharp,
    VerifiedUserSharp,
    ExitToAppSharp,

    SystemUpdate,
    ViewColumn,
    ViewList,
    ViewListSharp,
    Menu,
    ZoomIn,
    ZoomOut
} from '@mui/icons-material'
export { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
export { faSpinner } from '@fortawesome/free-solid-svg-icons'
// export { TagIcon }